Aluna: Isabela Almeida Marinho da Silveira

Especialização: Data Science e Analytics - Senai Cimatec

Disciplina: Técnicas de Reconhecimento de Padrões

**Dataset:** heart_disease

**Dicionário de dados:**

**age:** idade

**sex:** sexo (1 masculino e 0 feminino)

**chest pain type:** tipo de dor no peito (4 valores)

**resting blood pressure:** pressão arterial em repouso

**serum cholestoral in mg/dl:** colesterol sérico em mg/dl

**fasting blood sugar > 120 mg/dl:** açúcar no sangue em jejum > 120 mg/dl

**resting electrocardiographic results:** resultados eletrocardiográficos em repouso (valores 0,1,2)

**maximum heart rate achieved:** frequência cardíaca máxima alcançada

**exercise induced angina:** angina induzida por exercício

**oldpeak:** pico antigo = depressão do segmento ST induzida pelo exercício em relação ao repouso

**slope of peak:** a inclinação do pico do segmento ST do exercício

**number of major vessels:** número de vasos principais (0-3) coloridos por fluorosopia

**thal:** tal (0 = normal; 1 = defeito fixo; 2 = defeito reversível)


In [157]:
pip install pycaret

In [158]:
!pip install sweetviz

In [159]:
import pandas as pd
import sweetviz as sv
import numpy as np

In [160]:
from pycaret.datasets import get_data
from pycaret.classification import *

# Seleção de Conjunto de Dados:

O dataset escolhido é para classificação de diagnóstico de doença do coração.

In [161]:
dados = get_data('heart_disease')

age  sex  chest pain type  resting blood pressure  \
0   70    1                4                     130   
1   67    0                3                     115   
2   57    1                2                     124   
3   64    1                4                     128   
4   74    0                2                     120   

   serum cholestoral in mg/dl        fasting blood sugar > 120 mg/dl   \
0                               322                                 0   
1                               564                                 0   
2                               261                                 0   
3                               263                                 0   
4                               269                                 0   

   resting electrocardiographic results  maximum heart rate achieved    \
0                                     2                            109   
1                                     2                            160   
2                                     0                            141   
3                                     0                            105   
4                                     2                            121   

   exercise induced angina      oldpeak   slope of peak  \
0                            0       2.4              2   
1                            0       1.6              2   
2                            0       0.3              1   
3                            1       0.2              2   
4                            1       0.2              1   

   number of major vessels   thal  Disease  
0                         3     3        1  
1                         0     7        0  
2                         0     7        1  
3                         1     7        0  
4                         1     3        0

agora deve comparar os 3 datasets

In [162]:
dados.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 270 entries, 0 to 269
Data columns (total 14 columns):
 #   Column                                Non-Null Count  Dtype  
---  ------                                --------------  -----  
 0   age                                   270 non-null    int64  
 1   sex                                   270 non-null    int64  
 2   chest pain type                       270 non-null    int64  
 3   resting blood pressure                270 non-null    int64  
 4   serum cholestoral in mg/dl            270 non-null    int64  
 5   fasting blood sugar > 120 mg/dl       270 non-null    int64  
 6   resting electrocardiographic results  270 non-null    int64  
 7   maximum heart rate achieved           270 non-null    int64  
 8   exercise induced angina               270 non-null    int64  
 9   oldpeak                               270 non-null    float64
 10  slope of peak                         270 non-null    int64  
 11  number of major ves

In [163]:
dados.describe()

age         sex  chest pain type  resting blood pressure  \
count  270.000000  270.000000       270.000000              270.000000   
mean    54.433333    0.677778         3.174074              131.344444   
std      9.109067    0.468195         0.950090               17.861608   
min     29.000000    0.000000         1.000000               94.000000   
25%     48.000000    0.000000         3.000000              120.000000   
50%     55.000000    1.000000         3.000000              130.000000   
75%     61.000000    1.000000         4.000000              140.000000   
max     77.000000    1.000000         4.000000              200.000000   

       serum cholestoral in mg/dl        fasting blood sugar > 120 mg/dl   \
count                        270.000000                        270.000000   
mean                         249.659259                          0.148148   
std                           51.686237                          0.355906   
min                          126.000000                          0.000000   
25%                          213.000000                          0.000000   
50%                          245.000000                          0.000000   
75%                          280.000000                          0.000000   
max                          564.000000                          1.000000   

       resting electrocardiographic results  maximum heart rate achieved    \
count                            270.000000                     270.000000   
mean                               1.022222                     149.677778   
std                                0.997891                      23.165717   
min                                0.000000                      71.000000   
25%                                0.000000                     133.000000   
50%                                2.000000                     153.500000   
75%                                2.000000                     166.000000   
max                                2.000000                     202.000000   

       exercise induced angina       oldpeak   slope of peak  \
count                   270.000000  270.00000     270.000000   
mean                      0.329630    1.05000       1.585185   
std                       0.470952    1.14521       0.614390   
min                       0.000000    0.00000       1.000000   
25%                       0.000000    0.00000       1.000000   
50%                       0.000000    0.80000       2.000000   
75%                       1.000000    1.60000       2.000000   
max                       1.000000    6.20000       3.000000   

       number of major vessels         thal     Disease  
count                270.000000  270.000000  270.000000  
mean                   0.670370    4.696296    0.444444  
std                    0.943896    1.940659    0.497827  
min                    0.000000    3.000000    0.000000  
25%                    0.000000    3.000000    0.000000  
50%                    0.000000    3.000000    0.000000  
75%                    1.000000    7.000000    1.000000  
max                    3.000000    7.000000    1.000000

Dados balanceados considerando o target Disease com média em 0.44

In [164]:
eda = sv.analyze(source = dados, target_feat = 'Disease')

                                             |          | [  0%]   00:00 -> (? left)

In [165]:
eda.show_html()

Report SWEETVIZ_REPORT.html was generated! NOTEBOOK/COLAB USERS: the web browser MAY not pop up, regardless, the report IS saved in your notebook/colab files.


In [166]:
#remover espaço em branco do nome da coluna
dados.rename(columns=lambda x: x.strip(), inplace=True)

In [167]:
# ?setup

In [168]:
class_setup = setup(data = dados,
                    target = 'Disease',
                    numeric_features = ['age','resting blood pressure', 'serum cholestoral in mg/dl', 'maximum heart rate achieved', 'oldpeak'],
                    categorical_features = ['sex', 'chest pain type', 'fasting blood sugar > 120 mg/dl', 'resting electrocardiographic results', 'exercise induced angina', 'slope of peak', 'number of major vessels', 'thal'],
                    normalize = True,
                    normalize_method = 'minmax',
                    n_jobs = -1,
                    session_id = 238)  #Foi necessário fixar o seed para dar continuidade ao  trabalho, mesmo entendendo que na prática é necessário validar ao máximo os dados (sem fixar o seed)

In [169]:
modelos = compare_models()

Processing:   0%|          | 0/65 [00:00<?, ?it/s]

O recall mede a proporção de instâncias positivas previstas corretamente em relação ao total de instâncias positivas reais.
O recall é particularmente importante em casos onde os falsos negativos são mais críticos e tem implicações mais sérias do que os falsos positivos.

A precisão mede a proporção de instâncias positivas previstas corretamente em relação ao total de instâncias previstas como positivas.
A precisão é importante quando os falsos positivos são custosos.

O F1 Score é a média harmônica entre precisão e recall. Ele equilibra ambas as métricas e é útil quando há um desejo de encontrar um equilíbrio entre falsos positivos e falsos negativos.

Para a escolha do melhor modelo, é necessário levar em consideração o negócio.

# Formulação de Métrica de Custo:

Para formular a métrica de custo, onde o custo menor será o melhor caso, levei em consideração uma pontuação que favoreça o verdadeiro negativo (custo 0), ou seja, previu que não era doença e não era doença. Em seguida, favoreça o verdadeiro positivo, ou seja, previu que era doença e era doença (custo 1).

Em contrapartida, levei em consideração uma pontuação que desfavoreça mais o falso negativo (custo 4), ou seja, previu não doença e estava doente. Em seguida, desfavoreça o falso positivo (custo 2), ou seja, previu doença e não era doença.

Pelo entendimento, é mais grave o falso negativo, por ter implicações mais sérias tanto para o paciente quanto para a seguradora. Por esse motivo, o seu custo tem um peso maior, impactando diretamente na escolha do melhor modelo.

Os modelos serão analisados levando em consideração o menor custo possível.

In [170]:
# Criando uma métrica personalizada no PyCaret
def custo(y, y_pred):
    vp = np.where((y_pred==1) & (y==1), 1, 0)  # 1 previu doença e era doença -> custo do tratamento
    fp = np.where((y_pred==1) & (y==0), 2, 0)  # 2 previu doença e não era doença -> custo do tratamento, mas não era necessário
    vn = np.where((y_pred==0) & (y==0), 0, 0)  # 0 previu não doença e não era doença -> custo 0
    fn = np.where((y_pred==0) & (y==1), 4, 0)  # 4 previu não doença, mas estava doente -> pior caso do custo, custo do tratamento tardio e possível indenização judicial
    return np.sum([vp, fp, vn, fn])/len(y)

In [171]:
# add metric to PyCaret
#remove_metric('custo')
add_metric('custo', 'Custo', custo, greater_is_better = False)

Name                                                             Custo
Display Name                                                     Custo
Score Function       <pycaret.internal.metrics.EncodedDecodedLabels...
Scorer                     make_scorer(custo, greater_is_better=False)
Target                                                            pred
Args                                                                {}
Greater is Better                                                False
Multiclass                                                        True
Custom                                                            True
Name: custo, dtype: object

# Comparação de Métricas:

In [172]:
modelos = compare_models(sort = 'Custo')

Processing:   0%|          | 0/65 [00:00<?, ?it/s]

In [173]:
knn = create_model('knn')
knn_tunado = tune_model(knn, optimize = 'Custo')

Processing:   0%|          | 0/4 [00:00<?, ?it/s]

Processing:   0%|          | 0/7 [00:00<?, ?it/s]

Fitting 10 folds for each of 10 candidates, totalling 100 fits


In [174]:
knn = create_model('knn')
knn_tunado = tune_model(knn, optimize = 'F1')

Processing:   0%|          | 0/4 [00:00<?, ?it/s]

Processing:   0%|          | 0/7 [00:00<?, ?it/s]

Fitting 10 folds for each of 10 candidates, totalling 100 fits


In [175]:
et = create_model('et')
et_tunado = tune_model(et, optimize = 'Custo')

Processing:   0%|          | 0/4 [00:00<?, ?it/s]

Processing:   0%|          | 0/7 [00:00<?, ?it/s]

Fitting 10 folds for each of 10 candidates, totalling 100 fits


In [176]:
lda = create_model('lda')
lda_tunado = tune_model(lda, optimize = 'Custo')

Processing:   0%|          | 0/4 [00:00<?, ?it/s]

Processing:   0%|          | 0/7 [00:00<?, ?it/s]

Fitting 10 folds for each of 10 candidates, totalling 100 fits


In [177]:
svm = create_model('svm')
svm_tunado = tune_model(svm, optimize = 'Custo')

Processing:   0%|          | 0/4 [00:00<?, ?it/s]

Processing:   0%|          | 0/7 [00:00<?, ?it/s]

Fitting 10 folds for each of 10 candidates, totalling 100 fits


Analisando o resultado tunado dos três melhores modelos iniciais, o KNN continuou apresentando o menor custo (0.7980).

A maior diferença no custo entre o modelo básico e o modelo tunado foi para o Linear Discriminant Analysis.

Fiz mais um teste com o SVM, pois inicialmente ele foi o que teve melhor recall (0.7792), já que os falsos negativos são mais críticos, porém o custo foi maior que o custo do KNN. Comprovando que não basta analisar individualmente apenas uma métrica. Neste caso, a precisão era bem inferior que a precisão do KNN.

Como teste, também comparei os resultados da tunagem do KNN para diferentes métricas, comparando F1 e Custo, e foram exatamentes iguais.

# Análise do Cut-off Point:

In [178]:
cortes = np.arange(0.05, 1, 0.05)
print(cortes)

rec = []
pre = []
cus = []

for corte in cortes:
    predict_model(knn_tunado, probability_threshold = float(corte))
    metricas = pull()
    rec.append(metricas.loc[0, 'Recall'])
    pre.append(metricas.loc[0, 'Prec.'])
    cus.append(metricas.loc[0, 'Custo'])

pd.DataFrame({'Corte': cortes, 'Recall': rec, 'Precisão': pre, 'Custo': cus})

[0.05 0.1  0.15 0.2  0.25 0.3  0.35 0.4  0.45 0.5  0.55 0.6  0.65 0.7
 0.75 0.8  0.85 0.9  0.95]


Corte  Recall  Precisão   Custo
0    0.05  1.0000    0.5143  1.2840
1    0.10  1.0000    0.5714  1.1111
2    0.15  0.9444    0.6182  1.0370
3    0.20  0.9167    0.6600  0.9753
4    0.25  0.9167    0.6875  0.9259
5    0.30  0.9167    0.6875  0.9259
6    0.35  0.9167    0.7674  0.8025
7    0.40  0.9167    0.8049  0.7531
8    0.45  0.8611    0.8378  0.7778
9    0.50  0.8056    0.8529  0.8272
10   0.55  0.7500    0.8710  0.8765
11   0.60  0.6944    0.8929  0.9259
12   0.65  0.6667    0.9600  0.9136
13   0.70  0.6667    0.9600  0.9136
14   0.75  0.6389    1.0000  0.9259
15   0.80  0.3889    1.0000  1.2593
16   0.85  0.3333    1.0000  1.3333
17   0.90  0.1944    1.0000  1.5185
18   0.95  0.1111    1.0000  1.6296

In [179]:
knn_tunado

KNeighborsClassifier(algorithm='auto', leaf_size=30, metric='minkowski',
                     metric_params=None, n_jobs=-1, n_neighbors=18, p=2,
                     weights='distance')

Analisando o resultado para o modelo knn:


*   Custo para o modelo: 0.8778
*   Custo para o modelo tunado: 0.7980
*   Melhor corte verificado: 0.40
*   Custo no melhor corte: 0.7531



In [180]:
cortes = np.arange(0.05, 1, 0.05)
print(cortes)

rec = []
pre = []
cus = []

for corte in cortes:
    predict_model(et_tunado, probability_threshold = float(corte))
    metricas = pull()
    rec.append(metricas.loc[0, 'Recall'])
    pre.append(metricas.loc[0, 'Prec.'])
    cus.append(metricas.loc[0, 'Custo'])

pd.DataFrame({'Corte': cortes, 'Recall': rec, 'Precisão': pre, 'Custo': cus})

[0.05 0.1  0.15 0.2  0.25 0.3  0.35 0.4  0.45 0.5  0.55 0.6  0.65 0.7
 0.75 0.8  0.85 0.9  0.95]


Corte  Recall  Precisão   Custo
0    0.05  1.0000    0.4444  1.5556
1    0.10  1.0000    0.4675  1.4568
2    0.15  1.0000    0.5143  1.2840
3    0.20  1.0000    0.5902  1.0617
4    0.25  0.9722    0.6140  1.0247
5    0.30  0.9444    0.6667  0.9383
6    0.35  0.9167    0.7174  0.8765
7    0.40  0.8889    0.7442  0.8642
8    0.45  0.8889    0.7805  0.8148
9    0.50  0.8611    0.8158  0.8025
10   0.55  0.8333    0.8333  0.8148
11   0.60  0.8056    0.9062  0.7778
12   0.65  0.7500    0.9643  0.8025
13   0.70  0.6944    0.9615  0.8765
14   0.75  0.5833    0.9545  1.0247
15   0.80  0.4167    0.9375  1.2469
16   0.85  0.3333    1.0000  1.3333
17   0.90  0.1944    1.0000  1.5185
18   0.95  0.0833    1.0000  1.6667

In [181]:
et_tunado

ExtraTreesClassifier(bootstrap=False, ccp_alpha=0.0, class_weight='balanced',
                     criterion='entropy', max_depth=9, max_features='sqrt',
                     max_leaf_nodes=None, max_samples=None,
                     min_impurity_decrease=0.005, min_samples_leaf=5,
                     min_samples_split=5, min_weight_fraction_leaf=0.0,
                     n_estimators=210, n_jobs=-1, oob_score=False,
                     random_state=238, verbose=0, warm_start=False)

Analisando o resultado para o modelo et:


*   Custo para o modelo: 0.8927
*   Custo para o modelo tunado: 0.8611
*   Melhor corte verificado: 0.60
*   Custo no melhor corte: 0.7778

In [182]:
cortes = np.arange(0.05, 1, 0.05)
print(cortes)

rec = []
pre = []
cus = []

for corte in cortes:
    predict_model(lda_tunado, probability_threshold = float(corte))
    metricas = pull()
    rec.append(metricas.loc[0, 'Recall'])
    pre.append(metricas.loc[0, 'Prec.'])
    cus.append(metricas.loc[0, 'Custo'])

pd.DataFrame({'Corte': cortes, 'Recall': rec, 'Precisão': pre, 'Custo': cus})

[0.05 0.1  0.15 0.2  0.25 0.3  0.35 0.4  0.45 0.5  0.55 0.6  0.65 0.7
 0.75 0.8  0.85 0.9  0.95]


Corte  Recall  Precisão   Custo
0    0.05  0.9167    0.6875  0.9259
1    0.10  0.9167    0.6875  0.9259
2    0.15  0.8889    0.7273  0.8889
3    0.20  0.8889    0.7273  0.8889
4    0.25  0.8889    0.7619  0.8395
5    0.30  0.8889    0.7619  0.8395
6    0.35  0.8889    0.7805  0.8148
7    0.40  0.8889    0.7805  0.8148
8    0.45  0.8889    0.8205  0.7654
9    0.50  0.8889    0.8649  0.7160
10   0.55  0.8889    0.8649  0.7160
11   0.60  0.8889    0.8889  0.6914
12   0.65  0.8889    0.9143  0.6667
13   0.70  0.8889    0.9143  0.6667
14   0.75  0.8889    0.9143  0.6667
15   0.80  0.8611    0.9118  0.7037
16   0.85  0.8333    0.9677  0.6914
17   0.90  0.7500    0.9643  0.8025
18   0.95  0.6667    0.9600  0.9136

In [183]:
lda_tunado

LinearDiscriminantAnalysis(covariance_estimator=None, n_components=None,
                           priors=None, shrinkage=0.7, solver='eigen',
                           store_covariance=False, tol=0.0001)

Analisando o resultado para o modelo lda:


*   Custo para o modelo: 0.9243
*   Custo para o modelo tunado: 0.8243
*   Melhor corte verificado: 0.65
*   Custo no melhor corte: 0.6667

Com base na análise realizada, o melhor resultado levando em consideração o menor custo (0.6667) foi para o modelo Linear Discriminant Analysis, com a linha de corte em 65%. Apesar de aumentar a possibilidade para o erro mais crítico, falso negativo, com o corte maior, foi o que apresentou uma boa relação do recall (0.8889) e da precisão (0.9143) comparando com os resultados apresentados do KNN na melhor linha de corte (40%).

Esse modelo surpreendeu no resultado final já que inicialmente não apresentou o melhor (menor) custo.



In [184]:
optimize_threshold(lda_tunado, optimize='Custo')

optimization loop finished successfully. Best threshold: 0.328125 with Custo=0.8348


CustomProbabilityThresholdClassifier(classifier=LinearDiscriminantAnalysis(covariance_estimator=None,
                                                                           n_components=None,
                                                                           priors=None,
                                                                           shrinkage=0.7,
                                                                           solver='eigen',
                                                                           store_covariance=False,
                                                                           tol=0.0001),
                                     covariance_estimator=None,
                                     n_components=None, priors=None,
                                     probability_threshold=0.328125,
                                     shrinkage=0.7, solver='eigen',
                                     store_covariance=False, tol=0.0001)

In [185]:
evaluate_model(lda_tunado)

interactive(children=(ToggleButtons(description='Plot Type:', icons=('',), options=(('Pipeline Plot', 'pipelin…

# Combinação de Modelos:

In [186]:
modelos = compare_models(n_select = 18)

Processing:   0%|          | 0/79 [00:00<?, ?it/s]

In [187]:
#?blend_models

In [188]:
# Combinado 1, pegando os três melhores modelos em relação ao custo com o método hard
combinado1 = blend_models([modelos[0], modelos[1], modelos[2]], method = 'hard')

Processing:   0%|          | 0/6 [00:00<?, ?it/s]

In [189]:
# Mantendo os modelos do combinado 1, porém deixando o método de forma automática para o PyCaret decidir qual o melhor método
combinado2 = blend_models([modelos[0], modelos[1], modelos[2]], method = 'auto')

Processing:   0%|          | 0/6 [00:00<?, ?it/s]

In [190]:
# Combinado 3, pegando os dois modelos, que pelas análises anteriores (do trabalho) obtiveram um melhor custo, e o modelo NB
combinado3 = blend_models([modelos[0], modelos[2], modelos[4]], method = 'auto')

Processing:   0%|          | 0/6 [00:00<?, ?it/s]

In [191]:
# Combinado 4, pegando os dois modelos que pelas análises anteriores (do trabalho) obtiveram um melhor custo e o modelo RF
combinado4 = blend_models([modelos[0], modelos[2], modelos[5]], method = 'auto')

Processing:   0%|          | 0/6 [00:00<?, ?it/s]

In [192]:
# Mantendo os modelos do combinado 2 com os modelos tunados
combinado5 = blend_models([knn_tunado, et_tunado, lda_tunado], method = 'auto')

Processing:   0%|          | 0/6 [00:00<?, ?it/s]

In [193]:
cortes = np.arange(0.05, 1, 0.05)
print(cortes)

rec = []
pre = []
cus = []

for corte in cortes:
    predict_model(combinado5, probability_threshold = float(corte))
    metricas = pull()
    rec.append(metricas.loc[0, 'Recall'])
    pre.append(metricas.loc[0, 'Prec.'])
    cus.append(metricas.loc[0, 'Custo'])

import pandas as pd
pd.DataFrame({'Corte': cortes, 'Recall': rec, 'Precisão': pre, 'Custo': cus})


[0.05 0.1  0.15 0.2  0.25 0.3  0.35 0.4  0.45 0.5  0.55 0.6  0.65 0.7
 0.75 0.8  0.85 0.9  0.95]


Corte  Recall  Precisão   Custo
0    0.05  1.0000    0.4737  1.4321
1    0.10  1.0000    0.5625  1.1358
2    0.15  0.9444    0.6538  0.9630
3    0.20  0.9167    0.6735  0.9506
4    0.25  0.9167    0.6875  0.9259
5    0.30  0.9167    0.7500  0.8272
6    0.35  0.8889    0.7442  0.8642
7    0.40  0.8889    0.8000  0.7901
8    0.45  0.8889    0.8000  0.7901
9    0.50  0.8889    0.8649  0.7160
10   0.55  0.8611    0.8857  0.7284
11   0.60  0.8611    0.9118  0.7037
12   0.65  0.8333    0.9091  0.7407
13   0.70  0.7500    0.9643  0.8025
14   0.75  0.6944    0.9615  0.8765
15   0.80  0.6667    0.9600  0.9136
16   0.85  0.4722    1.0000  1.1481
17   0.90  0.3333    1.0000  1.3333
18   0.95  0.1389    1.0000  1.5926

O combinado 5, com o blend dos modelos tunados dos três melhores modelos em relação ao custo, teve o melhor resultado (menor custo) em relação aos outros blends, porém o modelo Linear Discriminant Analysis isoladamente ainda teve o melhor resultado geral quando comparado a linha de corte.

Combinado 5 -> Custo de 0.7037 para a linha de corte em 60%

Linear Discriminant Analysis -> Custo de 0.6667 para a linha de corte em 65%


# Regressão Logística:

In [194]:
lr = create_model('lr')
lr_tunado = tune_model(lr, optimize = 'Custo')

Processing:   0%|          | 0/4 [00:00<?, ?it/s]

Processing:   0%|          | 0/7 [00:00<?, ?it/s]

Fitting 10 folds for each of 10 candidates, totalling 100 fits


In [195]:
lr_tunado

LogisticRegression(C=1.459, class_weight='balanced', dual=False,
                   fit_intercept=True, intercept_scaling=1, l1_ratio=None,
                   max_iter=1000, multi_class='auto', n_jobs=None, penalty='l2',
                   random_state=238, solver='lbfgs', tol=0.0001, verbose=0,
                   warm_start=False)

In [196]:
cortes = np.arange(0.60, 0.70, 0.01)
print(cortes)

rec = []
pre = []
cus = []

for corte in cortes:
    predict_model(lr_tunado, probability_threshold = float(corte))
    metricas = pull()
    rec.append(metricas.loc[0, 'Recall'])
    pre.append(metricas.loc[0, 'Prec.'])
    cus.append(metricas.loc[0, 'Custo'])

pd.DataFrame({'Corte': cortes, 'Recall': rec, 'Precisão': pre, 'Custo': cus})

[0.6  0.61 0.62 0.63 0.64 0.65 0.66 0.67 0.68 0.69]


Corte  Recall  Precisão   Custo
0   0.60  0.8889    0.8649  0.7160
1   0.61  0.8889    0.8649  0.7160
2   0.62  0.8889    0.8649  0.7160
3   0.63  0.8889    0.8889  0.6914
4   0.64  0.8889    0.8889  0.6914
5   0.65  0.8889    0.8889  0.6914
6   0.66  0.8889    0.9143  0.6667
7   0.67  0.8611    0.9394  0.6790
8   0.68  0.8611    0.9394  0.6790
9   0.69  0.8611    0.9394  0.6790

In [197]:
cortes = np.arange(0.60, 0.70, 0.01)
print(cortes)

rec = []
pre = []
cus = []

for corte in cortes:
    predict_model(lda_tunado, probability_threshold = float(corte))
    metricas = pull()
    rec.append(metricas.loc[0, 'Recall'])
    pre.append(metricas.loc[0, 'Prec.'])
    cus.append(metricas.loc[0, 'Custo'])

pd.DataFrame({'Corte': cortes, 'Recall': rec, 'Precisão': pre, 'Custo': cus})

[0.6  0.61 0.62 0.63 0.64 0.65 0.66 0.67 0.68 0.69]


Corte  Recall  Precisão   Custo
0   0.60  0.8889    0.8889  0.6914
1   0.61  0.8889    0.9143  0.6667
2   0.62  0.8889    0.9143  0.6667
3   0.63  0.8889    0.9143  0.6667
4   0.64  0.8889    0.9143  0.6667
5   0.65  0.8889    0.9143  0.6667
6   0.66  0.8889    0.9143  0.6667
7   0.67  0.8889    0.9143  0.6667
8   0.68  0.8889    0.9143  0.6667
9   0.69  0.8889    0.9143  0.6667

Comparando o resultado do modelo Logistic Regression tunado e do modelo Linear Discriminant Analysis tunado para a métrica Custo foi bem parecido, custo de 0.667 para a linha de corte 0.66 e 0.61 respectivamente.

O objetivo fundamental da LDA é encontrar a combinação linear de características que melhor separa as classes no espaço de características. Maximiza a separação entre as médias das classes enquanto minimiza a dispersão dentro das classes.

A Regressão Logística, por outro lado, modela a relação entre as características e a probabilidade de pertencer a uma determinada classe. Utiliza a função logística para transformar uma combinação linear de características em uma probabilidade.

In [198]:
dados.head()

age  sex  chest pain type  resting blood pressure  \
0   70    1                4                     130   
1   67    0                3                     115   
2   57    1                2                     124   
3   64    1                4                     128   
4   74    0                2                     120   

   serum cholestoral in mg/dl  fasting blood sugar > 120 mg/dl  \
0                         322                                0   
1                         564                                0   
2                         261                                0   
3                         263                                0   
4                         269                                0   

   resting electrocardiographic results  maximum heart rate achieved  \
0                                     2                          109   
1                                     2                          160   
2                                     0                          141   
3                                     0                          105   
4                                     2                          121   

   exercise induced angina  oldpeak  slope of peak  number of major vessels  \
0                        0      2.4              2                        3   
1                        0      1.6              2                        0   
2                        0      0.3              1                        0   
3                        1      0.2              2                        1   
4                        1      0.2              1                        1   

   thal  Disease  
0     3        1  
1     7        0  
2     7        1  
3     7        0  
4     3        0

In [199]:
coefs = lr_tunado.coef_

In [200]:
lr_tunado.intercept_

array([-1.38388929])

In [201]:
vars = get_config('X_train_transformed').columns.tolist()

In [202]:
pd.DataFrame({'Variável': vars, 'Coeficientes': coefs[0], 'Razão de Chances': np.exp(coefs[0])})

Variável  Coeficientes  Razão de Chances
0                                        age      0.152086          1.164260
1                                        sex      1.172012          3.228481
2                        chest pain type_4.0      1.167968          3.215453
3                        chest pain type_3.0     -0.647273          0.523471
4                        chest pain type_2.0     -0.183053          0.832724
5                        chest pain type_1.0     -0.337849          0.713303
6                     resting blood pressure      0.943563          2.569119
7                 serum cholestoral in mg/dl      1.675225          5.339996
8            fasting blood sugar > 120 mg/dl      0.171190          1.186716
9   resting electrocardiographic results_2.0      0.142581          1.153247
10  resting electrocardiographic results_0.0     -0.390302          0.676852
11  resting electrocardiographic results_1.0      0.247514          1.280837
12               maximum heart rate achieved     -0.754222          0.470376
13                   exercise induced angina      0.295353          1.343601
14                                   oldpeak      1.426466          4.163959
15                         slope of peak_2.0      0.294951          1.343060
16                         slope of peak_1.0     -0.489277          0.613070
17                         slope of peak_3.0      0.194119          1.214241
18               number of major vessels_0.0     -1.231808          0.291765
19               number of major vessels_1.0      0.272067          1.312675
20               number of major vessels_2.0      0.678737          1.971386
21               number of major vessels_3.0      0.280797          1.324185
22                                  thal_7.0      0.781081          2.183832
23                                  thal_3.0     -0.633917          0.530510
24                                  thal_6.0     -0.147371          0.862974

In [203]:
coefs[0]

array([ 0.15208573,  1.17201175,  1.16796833, -0.64727329, -0.1830528 ,
       -0.33784943,  0.94356297,  1.67522483,  0.17118992,  0.14258109,
       -0.39030219,  0.24751391, -0.75422229,  0.29535337,  1.42646629,
        0.29495055, -0.48927682,  0.19411908, -1.23180826,  0.27206692,
        0.6787367 ,  0.28079745,  0.78108095, -0.63391702, -0.14737112])

In [204]:
vars = ['age','resting blood pressure', 'serum cholestoral in mg/dl', 'maximum heart rate achieved', 'oldpeak']

In [205]:
dados_backup = dados.copy()

In [206]:
for variavel in vars:
    dados[variavel] = pd.qcut(dados[variavel], [0, 0.25, 0.5, 0.75, 1], duplicates = 'drop')

In [207]:
dados.head()

age  sex  chest pain type resting blood pressure  \
0  (61.0, 77.0]    1                4         (120.0, 130.0]   
1  (61.0, 77.0]    0                3        (93.999, 120.0]   
2  (55.0, 61.0]    1                2         (120.0, 130.0]   
3  (61.0, 77.0]    1                4         (120.0, 130.0]   
4  (61.0, 77.0]    0                2        (93.999, 120.0]   

  serum cholestoral in mg/dl  fasting blood sugar > 120 mg/dl  \
0             (280.0, 564.0]                                0   
1             (280.0, 564.0]                                0   
2             (245.0, 280.0]                                0   
3             (245.0, 280.0]                                0   
4             (245.0, 280.0]                                0   

   resting electrocardiographic results maximum heart rate achieved  \
0                                     2             (70.999, 133.0]   
1                                     2              (153.5, 166.0]   
2                                     0              (133.0, 153.5]   
3                                     0             (70.999, 133.0]   
4                                     2             (70.999, 133.0]   

   exercise induced angina        oldpeak  slope of peak  \
0                        0     (1.6, 6.2]              2   
1                        0     (0.8, 1.6]              2   
2                        0  (-0.001, 0.8]              1   
3                        1  (-0.001, 0.8]              2   
4                        1  (-0.001, 0.8]              1   

   number of major vessels  thal  Disease  
0                        3     3        1  
1                        0     7        0  
2                        0     7        1  
3                        1     7        0  
4                        1     3        0

In [208]:
dados.columns.tolist()[:-1]

['age',
 'sex',
 'chest pain type',
 'resting blood pressure',
 'serum cholestoral in mg/dl',
 'fasting blood sugar > 120 mg/dl',
 'resting electrocardiographic results',
 'maximum heart rate achieved',
 'exercise induced angina',
 'oldpeak',
 'slope of peak',
 'number of major vessels',
 'thal']

In [209]:
class_setup = setup(data = dados,
                    target = 'Disease',
                    categorical_features = dados.columns.tolist()[:-1],
                    n_jobs = -1,
                    session_id = 238)

In [210]:
# add metric to PyCaret
#remove_metric('custo')
add_metric('custo', 'Custo', custo, greater_is_better = False)

Name                                                             Custo
Display Name                                                     Custo
Score Function       <pycaret.internal.metrics.EncodedDecodedLabels...
Scorer                     make_scorer(custo, greater_is_better=False)
Target                                                            pred
Args                                                                {}
Greater is Better                                                False
Multiclass                                                        True
Custom                                                            True
Name: custo, dtype: object

In [211]:
lr = create_model('lr')
lr_tunado = tune_model(lr, optimize = 'Custo')

Processing:   0%|          | 0/4 [00:00<?, ?it/s]

Processing:   0%|          | 0/7 [00:00<?, ?it/s]

Fitting 10 folds for each of 10 candidates, totalling 100 fits


O resultado dessas transformações dos dados piorou o custo para o modelo LR.

# Balanceamento:

In [220]:
dados = dados_backup.copy()

In [221]:
dados.head()

age  sex  chest pain type  resting blood pressure  \
0   70    1                4                     130   
1   67    0                3                     115   
2   57    1                2                     124   
3   64    1                4                     128   
4   74    0                2                     120   

   serum cholestoral in mg/dl  fasting blood sugar > 120 mg/dl  \
0                         322                                0   
1                         564                                0   
2                         261                                0   
3                         263                                0   
4                         269                                0   

   resting electrocardiographic results  maximum heart rate achieved  \
0                                     2                          109   
1                                     2                          160   
2                                     0                          141   
3                                     0                          105   
4                                     2                          121   

   exercise induced angina  oldpeak  slope of peak  number of major vessels  \
0                        0      2.4              2                        3   
1                        0      1.6              2                        0   
2                        0      0.3              1                        0   
3                        1      0.2              2                        1   
4                        1      0.2              1                        1   

   thal  Disease  
0     3        1  
1     7        0  
2     7        1  
3     7        0  
4     3        0

In [222]:
# CRIAÇÃO DE UMA BASE PARA VALIDAÇÃO

aux = dados.sample(frac=1)
teste = aux.iloc[:81]
treino = aux.iloc[81:]

treino.reset_index(drop = True, inplace = True)
teste.reset_index(drop = True, inplace = True)

print(treino.shape)
print(teste.shape)

(189, 14)
(81, 14)


##  UNDERSAMPLING

In [223]:
# 1. SEPARAR A BASE EM DUAS, DE ACORDO COM A VARIAVEL RESPOSTA
dados0 = treino[treino['Disease'] == 0]
dados1 = treino[treino['Disease'] == 1]
print(dados0.shape)
print(dados1.shape)

(108, 14)
(81, 14)


In [224]:
# 2. RETIRAR UMA AMOSTRA ALEATORIA DA BASE MAIOR, DO TAMANHO DA BASE MENOR
amostra0 = dados0.sample(81)

# 3. JUNTAR A AMOSTRA COM A BASE E FORMAR O CONJUNTO DE DADOS PARA MODELAGEM
dados_under = pd.concat([amostra0, dados1])
dados_under.shape

(162, 14)

## OVERSAMPLING

In [225]:
maior = pd.concat(2*[dados1])
amostra1 = maior.sample(108)

dados_over = pd.concat([dados0, amostra1])
dados_over.reset_index(drop = True, inplace = True)
dados_over.shape

(216, 14)

## Testando os balanceamentos

In [226]:
dados_under.head()

age  sex  chest pain type  resting blood pressure  \
66    44    0                3                     118   
106   68    1                3                     118   
177   54    1                3                     125   
162   65    0                3                     155   
164   62    0                4                     140   

     serum cholestoral in mg/dl  fasting blood sugar > 120 mg/dl  \
66                          242                                0   
106                         277                                0   
177                         273                                0   
162                         269                                0   
164                         394                                0   

     resting electrocardiographic results  maximum heart rate achieved  \
66                                      0                          149   
106                                     0                          151   
177                                     2                          152   
162                                     0                          148   
164                                     2                          157   

     exercise induced angina  oldpeak  slope of peak  number of major vessels  \
66                         0      0.3              2                        1   
106                        0      1.0              1                        1   
177                        0      0.5              3                        1   
162                        0      0.8              1                        0   
164                        0      1.2              2                        0   

     thal  Disease  
66      3        0  
106     7        0  
177     3        0  
162     3        0  
164     3        0

In [227]:
class_setup = setup(data = dados_under,
                    target = 'Disease',
                    numeric_features = ['age','resting blood pressure', 'serum cholestoral in mg/dl', 'maximum heart rate achieved', 'oldpeak'],
                    categorical_features = ['sex', 'chest pain type', 'fasting blood sugar > 120 mg/dl', 'resting electrocardiographic results', 'exercise induced angina', 'slope of peak', 'number of major vessels', 'thal'],
                    normalize = True,
                    normalize_method = 'minmax',
                    n_jobs = -1,
                    session_id = 238)  #Foi necessário fixar o seed para dar continuidade ao  trabalho, mesmo entendendo que na prática é necessário validar ao máximo os dados (sem fixar o seed)

In [228]:
# add metric to PyCaret
#remove_metric('custo')
add_metric('custo', 'Custo', custo, greater_is_better = False)

Name                                                             Custo
Display Name                                                     Custo
Score Function       <pycaret.internal.metrics.EncodedDecodedLabels...
Scorer                     make_scorer(custo, greater_is_better=False)
Target                                                            pred
Args                                                                {}
Greater is Better                                                False
Multiclass                                                        True
Custom                                                            True
Name: custo, dtype: object

In [229]:
modelos = compare_models(sort = 'Custo')

Processing:   0%|          | 0/65 [00:00<?, ?it/s]

In [230]:
lr = create_model('lr')
lr_tunado = tune_model(lr, optimize = 'Custo')

Processing:   0%|          | 0/4 [00:00<?, ?it/s]

Processing:   0%|          | 0/7 [00:00<?, ?it/s]

Fitting 10 folds for each of 10 candidates, totalling 100 fits


In [231]:
dados_over.head()

age  sex  chest pain type  resting blood pressure  \
0   46    0                3                     142   
1   44    1                3                     140   
2   67    0                4                     106   
3   71    0                4                     112   
4   48    1                2                     130   

   serum cholestoral in mg/dl  fasting blood sugar > 120 mg/dl  \
0                         177                                0   
1                         235                                0   
2                         223                                0   
3                         149                                0   
4                         245                                0   

   resting electrocardiographic results  maximum heart rate achieved  \
0                                     2                          160   
1                                     2                          180   
2                                     0                          142   
3                                     0                          125   
4                                     2                          180   

   exercise induced angina  oldpeak  slope of peak  number of major vessels  \
0                        1      1.4              3                        0   
1                        0      0.0              1                        0   
2                        0      0.3              1                        2   
3                        0      1.6              2                        0   
4                        0      0.2              2                        0   

   thal  Disease  
0     3        0  
1     3        0  
2     3        0  
3     3        0  
4     3        0

In [232]:
class_setup = setup(data = dados_over,
                    target = 'Disease',
                    numeric_features = ['age','resting blood pressure', 'serum cholestoral in mg/dl', 'maximum heart rate achieved', 'oldpeak'],
                    categorical_features = ['sex', 'chest pain type', 'fasting blood sugar > 120 mg/dl', 'resting electrocardiographic results', 'exercise induced angina', 'slope of peak', 'number of major vessels', 'thal'],
                    normalize = True,
                    normalize_method = 'minmax',
                    n_jobs = -1,
                    session_id = 238)  #Foi necessário fixar o seed para dar continuidade ao  trabalho, mesmo entendendo que na prática é necessário validar ao máximo os dados (sem fixar o seed)

In [233]:
# add metric to PyCaret
#remove_metric('custo')
add_metric('custo', 'Custo', custo, greater_is_better = False)

Name                                                             Custo
Display Name                                                     Custo
Score Function       <pycaret.internal.metrics.EncodedDecodedLabels...
Scorer                     make_scorer(custo, greater_is_better=False)
Target                                                            pred
Args                                                                {}
Greater is Better                                                False
Multiclass                                                        True
Custom                                                            True
Name: custo, dtype: object

In [234]:
modelos = compare_models(sort = 'Custo')

Processing:   0%|          | 0/65 [00:00<?, ?it/s]

In [235]:
xgboost = create_model('xgboost')
xgboost_tunado = tune_model(xgboost, optimize = 'Custo')

Processing:   0%|          | 0/4 [00:00<?, ?it/s]

Processing:   0%|          | 0/7 [00:00<?, ?it/s]

Fitting 10 folds for each of 10 candidates, totalling 100 fits


Original model was better than the tuned model, hence it will be returned. NOTE: The display metrics are for the tuned model (not the original one).


Finalizando o trabalho, fiz o teste do balanceamento.

O dataset original já estava num balanceamento considerável OK (com uma média de 0.444444 para a variável target).

Utilizando a técnica de balanceamento undersampling, o melhor modelo foi LR tunado, com o custo de 0.9076.

Utilizando a técnica de balanceamento oversampling, o melhor modelo foi xgboost (sem tunar), com o custo de 0.7671. Considerado o melhor custo, sem análise da linha de corte, comparando com o KNN que obteve o custo de 0.7980 na análise inicial do trabalho.

